In [4]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
from ast import literal_eval
import psycopg2
#from config import db_password
db_password =

In [11]:
data_file = 'Database/recipes_for_SQL.csv'
cuisine_df = pd.read_csv(data_file, index_col=[0])
cuisine_df.head(10)

,cuisine_SP,cumin,onion,garlic,vanilla,lemon,bell pepper,tomato,chocolate,mushrooms,...,harissa,sprouts,squash blossoms,grapefruit,tamarind pulp,savory,baharat,douchi,sucralose,jicama
recipeid,,,,,,,,,,,,,,,,,,,,,
0,NaN,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NaN,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,NaN,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,NaN,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,NaN,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Indian,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,NaN,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
7,NaN,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
8,NaN,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,NaN,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/Recipes"
engine = create_engine(db_string)
cuisine_df.to_sql(name='cuisine_with_ingredents',con=engine, if_exists = 'replace')

In [9]:
encoded_file = "Database/fully_encoded_recipes_with_cuisine_from_SP.csv"
encoded_df = pd.read_csv(encoded_file)
encoded_df

,recipeid,cuisineid,onion,garlic,vanilla,lemon,bell pepper,tomato,chocolate,mushrooms,...,harissa,sprouts,squash blossoms,grapefruit,tamarind pulp,savory,baharat,douchi,sucralose,jicama
0,5,8,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,10,11,0,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,16,2,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,17,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,20,10,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2947,9978,11,1,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2948,9981,10,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2949,9984,10,0,1,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2950,9988,11,1,1,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2951,9989,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/Recipes"
engine = create_engine(db_string)
encoded_df.to_sql(name='Recipes_with_cuisines',con=engine, if_exists = 'replace')